# | Input Devices |
# Configure your input devices here. | https://mangowm.github.io/docs/configuration/input

# xkb_rules_layout = us

# If you want to disable pointer acceleration, uncomment the lines below.
 mouse_accel_profile = 0
 mouse_accel_speed = 0

 #Overview Setting
 hotarea_size=10
 enable_hotarea=1
 overcircle_center_ratio=0.5
 overviewgappi=5
 overviewgappo=30
