# | Outputs Configuration |
# Configure your monitors here or in the DMS "Displays" settings. | https://mangowm.github.io/docs/configuration/monitors
# Run `wlr-randr` to get your monitors information.
# You will have to remove "#" and edit it for it to take effect.

monitor_rule = name:DP-1, width:1980, height:1080, refresh:60.03, x:0, y:0, rr:0, vrr:1
monitor_rule = name:HDMI-A-2, width:1360, height:768, refresh:60.01, x:1920, y:0, rr:0, vrr:1
